MAKERSUITE_API_KEY="AIzaSyD_cmwp63gYxctcqGGV6mOnfYX7A4sjSu4"

DB_HOST="localhost"
DB_NAME="hnr24"
DB_USER="hnr24user"
DB_PASSWORD="password"

ADMIN_USERNAME="admin"
ADMIN_PASSWORD="admin"

SECRET_KEY="hNr24S3cr3T"